{%- if cookiecutter.role != "unset" %}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ cookiecutter.service_account }}
  namespace: {{ cookiecutter.namespace }}
  labels:
    app.kubernetes.io/name: {{ cookiecutter.project_slug }}
    app.kubernetes.io/instance: {{ cookiecutter.project_slug }}
{%- endif %}