{%- if cookiecutter.has_volume_0 %}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ cookiecutter.project_slug }}-{{ cookiecutter.volume_0_name }}-pvc
  namespace: {{ cookiecutter.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
{%- endif %}
{%- if cookiecutter.has_volume_1 %}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ cookiecutter.project_slug }}-{{ cookiecutter.volume_1_name }}-pvc
  namespace: {{ cookiecutter.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
{%- endif %}
{%- if cookiecutter.has_volume_2 %}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ cookiecutter.project_slug }}-{{ cookiecutter.volume_2_name }}-pvc
  namespace: {{ cookiecutter.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
{%- endif %}
{%- if cookiecutter.has_volume_3 %}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ cookiecutter.project_slug }}-{{ cookiecutter.volume_3_name }}-pvc
  namespace: {{ cookiecutter.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi  
{%- endif %}
{%- if cookiecutter.has_volume_4 %}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ cookiecutter.project_slug }}-{{ cookiecutter.volume_4_name }}-pvc
  namespace: {{ cookiecutter.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
{%- endif %}
