apiVersion: v1
kind: Service
metadata:
  name: {{ cookiecutter.project_slug }}-service
  namespace: {{ cookiecutter.namespace }}
spec:
  ports:
    - port: {{ cookiecutter.container_port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ cookiecutter.project_slug }}