---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{ cookiecutter.namespace }}
  name: {{ cookiecutter.project_slug }}-backup
spec:
  # Every day at 0300
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: restic
              image: docker.io/restic/restic:0.18.0
              command:
                - restic
                - "-r"
                - "s3:$(BUCKET_NAME)/{{ cookiecutter.cluster_name }}/{{ cookiecutter.project_slug }}-backup"
                - "--verbose"
                - "backup"
                - "/home/node/{{ cookiecutter.project_slug }}-data"
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: restic
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: restic
                      key: AWS_SECRET_ACCESS_KEY
                - name: RESTIC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: restic
                      key: RESTIC_PASSWORD
                - name: BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      name: restic
                      key: BUCKET_NAME
                - name: CLUSTER_NAME
                  valueFrom:
                    secretKeyRef:
                      name: restic
                      key: CLUSTER_NAME
                - name: RESTIC_HOST
                  valueFrom:
                    secretKeyRef:
                      name: restic
                      key: CLUSTER_NAME
              volumeMounts:
                {%- if cookiecutter.has_volume_0 %}
                - name: {{ cookiecutter.volume_0_name }}
                  mountPath: /home/node/{{ cookiecutter.project_slug }}-data/{{ cookiecutter.volume_0_name}}
                  readOnly: true
                {%- endif %}
                {%- if cookiecutter.has_volume_1 %}
                - name: {{ cookiecutter.volume_1_name }}
                  mountPath: /home/node/{{ cookiecutter.project_slug }}-data/{{ cookiecutter.volume_1_name }}
                  readOnly: false
                {%- endif %}
                {%- if cookiecutter.has_volume_2 %}
                - name: {{ cookiecutter.volume_2_name }}
                  mountPath: /home/node/{{ cookiecutter.project_slug }}-data/{{ cookiecutter.volume_2_name }}
                  readOnly: false
                {%- endif %} 
                {%- if cookiecutter.has_volume_3 %}
                - name: {{ cookiecutter.volume_3_name }}
                  mountPath: /home/node/{{ cookiecutter.project_slug }}-data/{{ cookiecutter.volume_3_name }}
                  readOnly: false
                {%- endif %}
                {%- if cookiecutter.has_volume_4 %}
                - name: {{ cookiecutter.volume_4_name }}
                  mountPath: /home/node/{{ cookiecutter.project_slug }}-data/{{ cookiecutter.volume_4_name }}
                  readOnly: false
                {%- endif %}
          volumes:
            {%- if cookiecutter.has_volume_0 %}
            - name: {{ cookiecutter.volume_0_name }}
              persistentVolumeClaim:
                claimName: {{ cookiecutter.project_slug }}-{{ cookiecutter.volume_0_name }}-pvc
            {%- endif %}
            {%- if cookiecutter.has_volume_1 %}
            - name: {{ cookiecutter.volume_1_name }}
              persistentVolumeClaim:
                claimName: {{ cookiecutter.project_slug }}-{{ cookiecutter.volume_1_name }}-pvc
            {%- endif %}
            {%- if cookiecutter.has_volume_2 %}
            - name: {{ cookiecutter.volume_2_name }}
              persistentVolumeClaim:
                claimName: {{ cookiecutter.project_slug }}-{{ cookiecutter.volume_2_name }}-pvc
            {%- endif %}
            {%- if cookiecutter.has_volume_3 %}
            - name: {{ cookiecutter.volume_3_name }}
              persistentVolumeClaim:
                claimName: {{ cookiecutter.project_slug }}-{{ cookiecutter.volume_3_name }}-pvc
            {%- endif %}
            {%- if cookiecutter.has_volume_4 %}
            - name: {{ cookiecutter.volume_4_name }}
              persistentVolumeClaim:
                claimName: {{ cookiecutter.project_slug }}-{{ cookiecutter.volume_4_name }}-pvc
            {%- endif %}

apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{ cookiecutter.namespace }}
  name: {{ cookiecutter.project_slug }}-backup-cleanup
spec:
  # Every day at 0400 after backups have run
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: restic
              image: docker.io/restic/restic:0.18.0
              command:
                - restic
                - "-r"
                - "s3:$(BUCKET_NAME):/{{ cookiecutter.cluster_name }}/{{ cookiecutter.project_slug }}-backup"
                - "--verbose"
                - "forget"
                - "--keep-last"
                - "5"
                - "--keep-weekly"
                - "3"
                - "--keep-monthly"
                - "1"
                - "--prune"
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: restic
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: restic
                      key: AWS_SECRET_ACCESS_KEY
                - name: RESTIC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: restic
                      key: RESTIC_PASSWORD
                - name: BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      name: restic
                      key: BUCKET_NAME
                - name: CLUSTER_NAME
                  valueFrom:
                    secretKeyRef:
                      name: restic
                      key: CLUSTER_NAME
                - name: RESTIC_HOST
                  valueFrom:
                    secretKeyRef:
                      name: restic
                      key: CLUSTER_NAME
